CREATE ROLE role_ro;
ALTER ROLE role_ro WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE role_rw;
ALTER ROLE role_rw WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE maindb_owner;
ALTER ROLE maindb_owner WITH LOGIN;

CREATE USER user_owner ENCRYPTED PASSWORD '123';
GRANT maindb_owner TO user_owner;

CREATE DATABASE maindb
    ENCODING = 'UTF8'
    LC_CTYPE = 'ru_RU.UTF-8'
    LC_COLLATE = 'ru_RU.UTF-8'
    TEMPLATE = template0
    OWNER = maindb_owner;

\c maindb

ALTER DATABASE maindb SET datestyle TO 'ISO, DMY';

ALTER DEFAULT PRIVILEGES FOR ROLE maindb_owner REVOKE SELECT ON SEQUENCES FROM role_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE maindb_owner REVOKE SELECT, USAGE ON SEQUENCES FROM role_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE maindb_owner REVOKE SELECT ON TABLES FROM role_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE maindb_owner REVOKE SELECT, INSERT, DELETE, UPDATE ON TABLES FROM role_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE maindb_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE user_owner GRANT SELECT ON SEQUENCES TO role_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE user_owner GRANT SELECT, USAGE ON SEQUENCES TO role_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE user_owner GRANT SELECT ON TABLES TO role_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE user_owner GRANT SELECT, INSERT, DELETE, UPDATE ON TABLES TO role_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE user_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE user_owner GRANT USAGE ON SCHEMAS TO role_ro,role_rw;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT ON SEQUENCES TO role_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT, USAGE ON SEQUENCES TO role_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT ON TABLES TO role_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT, INSERT, DELETE, UPDATE ON TABLES TO role_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT USAGE ON SCHEMAS TO role_ro,role_rw;

REVOKE ALL ON DATABASE maindb FROM public;

GRANT CONNECT ON DATABASE maindb TO maindb_owner;
